[package]
name = "basic_2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine_core = { path = "../engine_core" }
render = { path = "../render" }
